yolact_ros2_node:
  ros__parameters:
    yolact_path: /home/sumukh/RBE502_Robot_Control/drone_ws/src/yolact
    model_path: /home/sumukh/RBE502_Robot_Control/drone_ws/src/yolact/weights/yolact_base_54_800000.pth
    image_topic: /front/image_raw
    use_compressed_image: False
    publish_visualization: True
    publish_detections: True
    display_visualization: False
    display_masks: True
    display_bboxes: True
    display_text: True
    display_scores: True
    display_fps: True
    score_threshold: 0.15
    crop_masks: True
    top_k: True
    publish_namespace: /yolact_ros2
